export const queryKeys = {
  accounts: ['accounts'] as const,
  subscribers: ['subscribers'] as const,
  dids: ['dids'] as const,
  extensions: ['extensions'] as const,
  voicemailBoxes: ['voicemail-boxes'] as const,
  voicemailMessages: ['voicemail-messages'] as const,
  ivr: ['ivr'] as const,
  inboundRoutes: ['inbound-routes'] as const,
  timeConditions: ['time-conditions'] as const,
  routingPolicies: ['routing-policies'] as const,
  registrations: ['registrations'] as const,
  dialogs: ['dialogs'] as const,
  dispatcher: ['dispatcher'] as const,
  dialplan: ['dialplan'] as const,
  trustTrusted: ['trust', 'trusted'] as const,
  trustAddresses: ['trust', 'addresses'] as const,
  lcrGateways: ['lcr', 'gateways'] as const,
  lcrRules: ['lcr', 'rules'] as const,
  lcrRuleTargets: ['lcr', 'rule-targets'] as const,
  reportsCdrs: ['reports', 'cdrs'] as const,
  reportsAcc: ['reports', 'acc'] as const,
  reportsMissedCalls: ['reports', 'missed-calls'] as const,
  domains: ['domains'] as const,
  domainAttrs: ['domains', 'attrs'] as const,
  dbaliases: ['dbaliases'] as const,
  version: ['version'] as const,
  health: ['health'] as const,
  ready: ['ready'] as const,
};
